# Generated by Django 5.1.4 on 2025-02-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_line_customuser_alternate_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notification_preferences',
        ),
    ]
